export enum NotificationType {
    NEW_MESSAGE = "NEW_MESSAGE",
    MESSAGE_CHANGED = "MESSAGE_CHANGED",
    MESSAGE_REMOVED = "MESSAGE_REMOVED",
    FRIEND_IN_REQUEST = "FRIEND_IN_REQUEST",
    FRIEND_IN_REQUEST_CANCELED = "FRIEND_IN_REQUEST_CANCELED",
    FRIEND_OUT_REQUEST_CANCELED = "FRIEND_OUT_REQUEST_CANCELED",
    FRIEND_ACCEPT = "FRIEND_ACCEPT",
    FRIEND_REMOVE = "FRIEND_REMOVE",
    NEW_CONVERSATION = "NEW_CONVERSATION",
    CONVERSATION_REMOVED = "CONVERSATION_REMOVED",
    CONVERSATION_CHANGED = "CONVERSATION_CHANGED",
}