export enum NotificationType {
    MESSAGE = "MESSAGE",
    FRIEND_IN_REQUEST = "FRIEND_IN-REQUEST",
    FRIEND_IN_REQUEST_CANCELED = "FRIEND_IN-REQUEST_CANCELED",
    FRIEND_OUT_REQUEST = "FRIEND_OUT-REQUEST",
    FRIEND_OUT_REQUEST_CANCELED = "FRIEND_OUT-REQUEST_CANCELED",
    FRIEND_ACCEPT = "FRIEND_ACCEPT",
    FRIEND_REMOVE = "FRIEND_REMOVE",
    NEW_CONVERSATION = "NEW_CONVERSATION",
}