export enum ResponseError {
    BAD_AUTH = "BAD_AUTH",
    BAD_REQUEST = "BAD_REQUEST",
    NO_VALID_DATA = "NO_VALID_DATA",
    NO_FIND = "NO_FIND",
    NO_ACCESS = "NO_ACCESS",
    SERVER_ERROR = "SERVER_ERROR"
}