"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const auth_1 = __importDefault(require("./api/auth"));
const doc_1 = __importDefault(require("./api/doc"));
const users_1 = __importDefault(require("./api/users"));
const user_1 = __importDefault(require("./api/user"));
const conversations_1 = __importDefault(require("./api/conversations"));
const messages_1 = __importDefault(require("./api/messages"));
const friends_1 = __importDefault(require("./api/friends"));
const router = express_1.default.Router();
router.use('/auth', auth_1.default);
router.use('/users', users_1.default);
router.use('/user', user_1.default);
router.use('/conversations', conversations_1.default);
router.use('/messages', messages_1.default);
router.use('/friends', friends_1.default);
router.get('/doc', doc_1.default);
exports.default = router;
